server:
  port: 8081

spring:
  application:
    name: gestionmascotas
  datasource:
    url: jdbc:mysql://mysql:3306/adoptapp_gestionmascota?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-sv.default.svc.cluster.local:8761/eureka/
  instance:
    prefer-ip-address: true