
apiVersion: v1
kind: Service
metadata:
  name: gestionmascotas
spec:
  type: NodePort
  selector:
    app: gestionmascotas
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestionmascotas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestionmascotas
  template:
    metadata:
      labels:
        app: gestionmascotas
    spec:
      containers:
      - name: gestionmascotas
        image: entenad0/gestionmascotas:02.02
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/adoptapp_gestionmascota?serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        - name: SPRING_DATASOURCE_PASSWORD
          value: password