server:
  port: 8060

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: adoptante-service
          uri: lb://ADOPTANTE-SERVICE
          predicates:
            - Path=/adoptante/**
          filters:
            - StripPrefix=1
        - id: protectora-service
          uri: lb://PROTECTORA-SERVICE
          predicates:
            - Path=/protectora/**
          filters:
            - StripPrefix=1
        - id: role-based-route
          uri: lb://SOME-SERVICE
          predicates:
            - Path=/protected/**
          filters:
            - name: RoleBasedFilter
              args:
                role: "ROLE_ADMIN"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jwt:
  secret: 18ac29eeac37421d6f36dc2ed31976382220f89fbf0706d1497c8362c500517e
