
apiVersion: v1
kind: Service
metadata:
  name: adoptante-service
spec:
  type: NodePort
  selector:
    app: adoptante-service
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30012
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoptante-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adoptante-service
  template:
    metadata:
      labels:
        app: adoptante-service
    spec:
      containers:
        - name: adoptante-service
          image: entenad0/adoptante-service:03.04
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-adoptante:3306/adoptapp_adoptante_db?serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password