server:
  port: 8082

spring:
  application:
    name: contactanos
  datasource:
    url: jdbc:mysql://mysql-contacto:3306/adoptapp_contactame?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-sv.default.svc.cluster.local:8761/eureka/
  instance:
    prefer-ip-address: true