apiVersion: v1
kind: Service
metadata:
  name: eureka-sv

spec:
  type: NodePort
  selector:
    app: eureka-sv
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-sv

spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-sv
  template:
    metadata:
      labels:
        app: eureka-sv
    spec:
      containers:
        - name: eureka-sv
          image: entenad0/eureka-sv:02.01
          ports:
            - containerPort: 8761