
apiVersion: v1
kind: Service
metadata:
  name: protectora-service
spec:
  type: NodePort
  selector:
    app: protectora-service
  ports:
    - port: 8050
      targetPort: 8050
      nodePort: 30010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protectora-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protectora-service
  template:
    metadata:
      labels:
        app: protectora-service
    spec:
      containers:
        - name: protectora-service
          image: entenad0/protectora-service:03.03
          ports:
            - containerPort: 8050
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/adoptapp_protectora-service?serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password