
apiVersion: v1
kind: Service
metadata:
  name: contactanos
spec:
  type: NodePort
  selector:
    app: contactanos
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactanos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contactanos
  template:
    metadata:
      labels:
        app: contactanos
    spec:
      containers:
        - name: contactanos
          image: entenad0/contactanos:03.02
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-contacto:3306/adoptapp_contactame?serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password